# Generated by Django 6.0.2 on 2026-02-13 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workout',
            old_name='exercise_name',
            new_name='exercise',
        ),
        migrations.AddField(
            model_name='workout',
            name='reps',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workout',
            name='sets',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workout',
            name='weight',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
