# Generated by Django 6.0.2 on 2026-02-15 10:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_exercise_name_workout_exercise_workout_reps_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workout',
            old_name='exercise',
            new_name='exercise_name',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='completed',
        ),
        migrations.AlterField(
            model_name='workout',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='workout',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
