# Generated by Django 6.0.2 on 2026-02-16 06:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_workout_date_alter_workout_exercise_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='date',
        ),
        migrations.AddField(
            model_name='workout',
            name='workout_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='workout',
            name='weight',
            field=models.FloatField(default=0),
        ),
    ]
