# Generated by Django 6.0.2 on 2026-02-16 08:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_workout_date_workout_workout_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_date', models.DateField(default=django.utils.timezone.now)),
                ('meal', models.CharField(max_length=50)),
                ('food_name', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('calories', models.PositiveIntegerField()),
                ('protein', models.FloatField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
